ALLOWED_TOKENS = {
    "ac", "accumulator", "air", "aisle", "alarm", "ammonia", "angle", "apparent",
    "aqi", "average", "battery", "blowdown", "blue", "boost", "brightness",
    "broken", "building", "bypass", "cable", "calendar", "call", "carbon",
    "changeover", "charge", "chilled", "cie", "circuitbreaker", "circulation",
    "closed", "co", "co2", "cogeneration", "coil", "cold", "color", "command",
    "common", "communication", "compressor", "concentration", "condensate",
    "condenser", "condensing", "conditioned", "conditioning", "conference",
    "control", "cooldown", "cooler", "cooling", "coolingperformanceratio",
    "count", "counter", "current", "damper", "dc", "deadband", "defrost",
    "dehumidification", "dehumidifier", "density", "detection", "detergent",
    "device", "dewpoint", "dial", "diameter", "differential", "dimmer",
    "direction", "disable", "discharge", "dishwasher", "distance", "diverting",
    "down", "drain", "dryer", "dutycycle", "dynamic", "east", "economizer",
    "efficiency", "electricalgrid", "electricconductivity", "electrostatic",
    "emergency", "end", "energy", "entering", "evaporative", "evaporator",
    "event", "exchange", "exercise", "exhaust", "expansion", "extent", "fabric",
    "fade", "failed", "fan", "filter", "filtration", "fire", "fivesecondrolling",
    "floor", "flowrate", "flue", "formaldehyde", "frequency", "frost", "gas",
    "generator", "glycol", "green", "ground", "group", "guidevane", "h2", "h2s",
    "hash", "heat", "heater", "heating", "high", "hot", "hsl", "hue", "humidification",
    "humidifier", "humidity", "id", "illuminance", "index", "injection", "inlet",
    "input", "intensity", "inter", "inverter", "irradiance", "isolation", "label",
    "lamp", "leak", "leaving", "level", "lighting", "limit", "line", "linearacceleration",
    "linearvelocity", "liquid", "load", "local", "loop", "lost", "low", "luminaire",
    "maintenance", "makeup", "mass", "massflow", "master", "match", "matched", "max",
    "mechanical", "medium", "message", "min", "mixed", "mixing", "mode", "motion",
    "motor", "neutral", "next", "no", "no2", "north", "nox", "o2", "occupancy",
    "occupied", "offset", "oil", "ongoing", "open", "optimal", "orientation", "output",
    "outside", "over", "overload", "override", "ozone", "panel", "particle", "percentage",
    "ph", "phase", "phase1", "phase2", "phase3", "pm0pt5", "pm10pt0", "pm1pt0",
    "pm2pt5", "pm4pt0", "position", "potable", "power", "powerfactor", "preheating",
    "pressure", "pressurization", "primary", "probability", "process", "production",
    "program", "protection", "pump", "purge", "rain", "rate", "reactive", "recirculation",
    "recovery", "rectifier", "red", "refrigerant", "relative", "release", "remaining",
    "request", "resistance", "return", "reversing", "riser", "room", "rootmeansquare",
    "rotationalvelocity", "run", "saturation", "scene", "schedule", "scrubber",
    "secondary", "seismic", "sensor", "setpoint", "shade", "side", "signal", "smoke",
    "so2", "soundpressurelevel", "source1", "source2", "south", "southeast",
    "southwest", "specificenthalpy", "speed", "spray", "stage", "start", "startup",
    "static", "status", "steam", "stop", "strength", "subcooling", "suction", "sump",
    "superheat", "supervisor", "supply", "sweeper", "switch", "sync", "tamper", "tank",
    "temperature", "tenminutefixed", "test", "thermal", "thermalefficiency",
    "thermally", "thirtysecondrolling", "tilt", "time", "timestamp", "torque", "total",
    "totaldissolvedsolids", "transducer", "ultraviolet", "unoccupied", "up", "user",
    "valve", "vapor", "ventilation", "voc", "voltage", "volume", "volumetricconcentration",
    "warmup", "waste", "water", "west", "wetbulb", "wheel", "wind", "window",
    "wireless", "xaxis", "xvalue", "yaxis", "yvalue", "zaxis", "zone"
}